#! /bin/sh

export curdir="/usr/local/theftdeterrentdaemon"
export predir=""

. ${curdir}/${predir}funcdefine

fn_define

export td_log_file=service.log

. ${curdir}/${predir}funcutil
. ${curdir}/${predir}funcdaemon

fn_syscreatelogdir

echo "Stop daemon..." >> ${td_log_dir}/${td_log_file}

fn_daemonstop