#!/bin/sh

export curdir="/usr/share/theftdeterrentclient"
export predir="theftdeterrentclient."

. ${curdir}/${predir}funcdefine

fn_define

export td_log_file=service.log

. ${curdir}/${predir}funcutil
. ${curdir}/${predir}funcagent

fn_syscreatelogdir

echo "Check agent status..." >> ${td_log_dir}/${td_log_file}

if ( fn_agentstatus ) ; then
    return 0
else
    return 1
fi