#!/bin/sh

export curdir="/usr/share/theftdeterrentclient"
export predir="theftdeterrentclient."

. ${curdir}/${predir}funcdefine

fn_define

export td_log_file=service.log

. ${curdir}/${predir}funcutil
. ${curdir}/${predir}funcagent

fn_syscreatelogdir

echo "Start agent..." >> ${td_log_dir}/${td_log_file}

fn_agentstart