#! /bin/sh

export curdir="/usr/local/theftdeterrentclient/guardian"
export predir=""

. ${curdir}/${predir}funcdefine

fn_define

export td_log_file=service.log

. ${curdir}/${predir}funcutil
. ${curdir}/${predir}funcguardian

fn_syscreatelogdir

echo "Stop guardian..." >> ${td_log_dir}/${td_log_file}

fn_guardianstop